<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9544" started-at="2016-07-06T07:26:52Z" finished-at="2016-07-06T07:27:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9544" started-at="2016-07-06T07:26:52Z" finished-at="2016-07-06T07:27:02Z">
      <class name="gurukulaAutomation.GurukulaTestNG3">
        <test-method status="PASS" signature="setUp()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="setUp" is-config="true" duration-ms="2654" started-at="2016-07-06T09:26:52Z" finished-at="2016-07-06T09:26:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="launch()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="launch" duration-ms="537" started-at="2016-07-06T09:26:55Z" description="Launching the site.." finished-at="2016-07-06T09:26:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="registernewaccount()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="registernewaccount" duration-ms="1721" started-at="2016-07-06T09:26:56Z" description="Executing Register new account Test Cases" finished-at="2016-07-06T09:26:57Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Because of some technical failure user is not registered]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Because of some technical failure user is not registered
	at gurukulaAutomation.GurukulaTestNG3.registernewaccount(GurukulaTestNG3.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registernewaccount -->
        <test-method status="PASS" signature="login()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="login" duration-ms="355" started-at="2016-07-06T09:26:57Z" description="Executing Login Test Cases" finished-at="2016-07-06T09:26:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="entities()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="entities" duration-ms="2047" started-at="2016-07-06T09:26:58Z" description="Executing Entities Test cases" finished-at="2016-07-06T09:27:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- entities -->
        <test-method status="FAIL" signature="account()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="account" duration-ms="1570" started-at="2016-07-06T09:27:00Z" description="Executing Account Test cases" finished-at="2016-07-06T09:27:01Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Because of some issues, settings cannot be changed.  Contact admin]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Because of some issues, settings cannot be changed.  Contact admin
	at gurukulaAutomation.GurukulaTestNG3.account(GurukulaTestNG3.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- account -->
        <test-method status="PASS" signature="logout()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="logout" duration-ms="293" started-at="2016-07-06T09:27:01Z" description="Executing Logout Test cases" finished-at="2016-07-06T09:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:gurukulaAutomation.GurukulaTestNG3@50f8360d]" name="tearDown" is-config="true" duration-ms="350" started-at="2016-07-06T09:27:02Z" finished-at="2016-07-06T09:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- gurukulaAutomation.GurukulaTestNG3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
